services:
  postgres:
    image: postgres:15-alpine
    container_name: payment-postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=payment_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d payment_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # rabbitmq:
  #   image: rabbitmq:3-management-alpine
  #   container_name: payment-rabbitmq
  #   restart: always
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=guest
  #     - RABBITMQ_DEFAULT_PASS=guest
  #   healthcheck:
  #     test: ["CMD-SHELL", "rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_local_alarms"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 20s

  payment-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-api
    restart: on-failure
    depends_on:
      postgres: # Atualizado para o novo nome
        condition: service_healthy
    environment:
      # Agora a URL aponta para @postgres em vez de @db
      - DB_URL=postgres://user:password@postgres:5432/payment_db?sslmode=disable
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - PORT=8080
      - MIGRATIONS_PATH=file://migrations
    ports:
      - "8080:8080"

volumes:
  postgres_data: